version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker build 
          command: docker build -t sports-oracle . 
      - run: 
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: 
          name: Push Docker image to repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
              docker tag sports-oracle anypay/sports-oracle:latest 
              docker push anypay/sports-oracle:latest
            fi
            docker tag sports-oracle anypay/sports-oracle:${CIRCLE_SHA1}
            docker push anypay/sports-oracle:${CIRCLE_SHA1}
      - run: 
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
              ssh ec2-user@54.163.44.177 ./start_app.sh
            fi
